services:
  audiosub:
    build:
      context: .
      network: host
    image: audiosub:latest
    environment:
      - PULSE_SERVER=unix:/run/user/${USER_ID:-1000}/pulse/native
      - AUDIOSUB_MODEL_PATH=/cache/audiosub/models/vosk-model-small-ru-0.22
    volumes:
      - /run/user/${USER_ID:-1000}/pulse:/run/user/${USER_ID:-1000}/pulse
      - ./output:/output
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    command: [
      "--device", "alsa_output.pci-0000_6e_00.6.analog-stereo.monitor",
      "--output", "/output/subtitles.srt"
    ]
