# ──────────────────────────────────────────────────────────────
# audiosub — справка
# ──────────────────────────────────────────────────────────────

.PHONY: help

help:
	@printf '\n'
	@printf '╭──────────────────────────────────────────────────────────────╮\n'
	@printf '│         $(BOLD)audiosub$(NC) — real-time automatic subtitles             │\n'
	@printf '╰──────────────────────────────────────────────────────────────╯\n'
	@printf '\n'
	@printf '  $(CYAN)использование:$(NC)  make $(GREEN)<цель>$(NC)\n'
	@printf '\n'
	@printf '  $(YELLOW)примечания:$(NC)\n'
	@printf '    Vosk   : требуется libvosk.so в /home/redalexdad/.local/lib/\n'
	@printf '              github.com/alphacep/vosk-api/releases\n'
	@printf '    Whisper: нужен WHISPER_DONT_GENERATE_BINDINGS=1, если bindgen падает\n'
	@printf '\n'
	@printf '$(CYAN)╭─ Сборка ─────────────────────────────────────────────────────────$(NC)\n'
	@printf '  $(GREEN)build$(NC)               Собрать проект\n'
	@printf '  $(GREEN)build-whisper$(NC)        Собрать с whisper backend\n'
	@printf '  $(GREEN)build-both$(NC)           Собрать с vosk + whisper (переключение в audiosub.toml)\n'
	@printf '  $(GREEN)release$(NC)              Release-сборка (Linux)\n'
	@printf '  $(GREEN)release-whisper$(NC)      Release-сборка с whisper\n'
	@printf '  $(GREEN)release-both$(NC)         Release-сборка с vosk + whisper\n'
	@printf '  $(GREEN)release-win$(NC)          Кросс-сборка для Windows (требуется mingw-w64)\n'
	@printf '  $(GREEN)release-mac$(NC)          Сборка для macOS (запускать на macOS)\n'
	@printf '$(CYAN)╰──────────────────────────────────────────────────────────────────$(NC)\n'
	@printf '\n'
	@printf '$(CYAN)╭─ Запуск ─────────────────────────────────────────────────────────$(NC)\n'
	@printf '  $(GREEN)run [ARGS]$(NC)           TUI-режим (q/Esc — выход)\n'
	@printf '  $(GREEN)run-whisper [ARGS]$(NC)   TUI-режим с whisper backend\n'
	@printf '  $(GREEN)run-both [ARGS]$(NC)      TUI-режим с vosk + whisper\n'
	@printf '  $(GREEN)cli [ARGS]$(NC)           Консольный режим (без TUI)\n'
	@printf '  $(GREEN)cli-whisper [ARGS]$(NC)   Консольный режим с whisper\n'
	@printf '$(CYAN)╰──────────────────────────────────────────────────────────────────$(NC)\n'
	@printf '\n'
	@printf '$(CYAN)╭─ Модели ────────────────────────────────────────────────────────$(NC)\n'
	@printf '  $(GREEN)model-download$(NC)       Скачать модель Vosk (русская)\n'
	@printf '  $(GREEN)model-whisper$(NC)        Скачать модель Whisper ggml-base\n'
	@printf '$(CYAN)╰──────────────────────────────────────────────────────────────────$(NC)\n'
	@printf '\n'
	@printf '$(CYAN)╭─ Проверка качества ─────────────────────────────────────────────$(NC)\n'
	@printf '  $(GREEN)test$(NC)                 Запустить тесты\n'
	@printf '  $(GREEN)check$(NC)                cargo check (быстрая проверка компиляции)\n'
	@printf '  $(GREEN)lint$(NC)                 cargo clippy\n'
	@printf '  $(GREEN)fmt$(NC)                  Проверить форматирование (cargo fmt --check)\n'
	@printf '  $(GREEN)verify$(NC)               Полный CI-конвейер: test → check → lint → fmt\n'
	@printf '  $(GREEN)ci-check$(NC)             Полная CI-симуляция (scripts/ci-check.sh)\n'
	@printf '$(CYAN)╰──────────────────────────────────────────────────────────────────$(NC)\n'
	@printf '\n'
	@printf '$(CYAN)╭─ Docker (compose v2) ────────────────────────────────────────────$(NC)\n'
	@printf '  $(GREEN)docker-deploy [ENGINE=vosk]$(NC)  build + up\n'
	@printf '  $(GREEN)docker-build [ENGINE=vosk]$(NC)   Собрать образ\n'
	@printf '  $(GREEN)docker-rebuild [ENGINE=vosk]$(NC) Пересобрать без кэша\n'
	@printf '  $(GREEN)docker-up$(NC)               Запустить контейнер\n'
	@printf '  $(GREEN)docker-down$(NC)             Остановить\n'
	@printf '  $(GREEN)docker-restart$(NC)          down + up\n'
	@printf '  $(GREEN)docker-clean$(NC)            Удалить образ\n'
	@printf '  $(GREEN)docker-logs$(NC)             Просмотр логов\n'
	@printf '  $(YELLOW)  ENGINE=whisper / ENGINE=both — для других бекендов$(NC)\n'
	@printf '$(CYAN)╰──────────────────────────────────────────────────────────────────$(NC)\n'
	@printf '\n'
	@printf '$(CYAN)╭─ Утилиты ───────────────────────────────────────────────────────$(NC)\n'
	@printf '  $(GREEN)clean$(NC)                Очистить артефакты сборки\n'
	@printf '  $(GREEN)report$(NC)               Создать шаблон отчёта в reports/\n'
	@printf '  $(GREEN)help$(NC)                 Показать это сообщение\n'
	@printf '$(CYAN)╰──────────────────────────────────────────────────────────────────$(NC)\n'
	@printf '\n'
	@printf '  $(YELLOW)примеры:$(NC)\n'
	@printf '    make model-download\n'
	@printf '    make run\n'
	@printf '    make run-whisper\n'
	@printf '    make run ARGS="-- --list-devices"\n'
	@printf '    make cli\n'
	@printf '    make deploy\n'
	@printf '\n'
